# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ExtractGenomeNameFromPath <- function(path) {
    .Call(`_MLSTyper_ExtractGenomeNameFromPath`, path)
}

GetGenomeNameWithExt <- function(path, ext) {
    .Call(`_MLSTyper_GetGenomeNameWithExt`, path, ext)
}

RunBlast <- function(fastaPaths, blastDB) {
    .Call(`_MLSTyper_RunBlast`, fastaPaths, blastDB)
}

